### ISSUE TITLE
Rewrite references to RTCIceGatherer

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-ice#10]
There are a couple references to RTCIceGatherer which is not defined in WebRTC-ICE (it's from ORTC).

* Step 6 of `start()`
* `addRemoteCandidate` description

**Comment by aboba** [comment]
In ORTC, calling `start` with a new `RTCIceGatherer` was ones means for initiating an ICE restart.  Currently, it is not clear whether `gather()` implies an ICE restart or not.

**Comment by aboba** [comment]
I think step 6 can be deleted, since there is no equivalent scenario that can occur in the current API.
