### ISSUE TITLE
Distinguishing between various RTCIceTransports

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-ice#13]
With this specification there will be three versions of the RTCIceTransport each with different interfaces and capabilities.

1. WebRTC-PC version. This is just an informational surface.
2. ORTC version. This uses an RTCIceGatherer.
3. WebRTC-ICE version. This is similar to WebRTC-PC but adds a control surface.

How will Web developers be able to distinguish between these when they all carry the same name? Do they need to check for methods in the prototype? Keep track of where they came from?

**Comment by aboba** [comment]
Today, ORTC is detected by checking for the existence of the `RTCIceGatherer`.  A way to detect the implementation of WebRTC-ICE would be if there is no `RTCIceGatherer`, but `RTCIceTransport.start()` exists.
