### ISSUE TITLE
Why is a new event type "localcandidate" introduced here?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-ice#16]
This seems to be exactly the same as the Peerconnection "icecandidate" event. Why does it have a new name in this specification?

**Comment by henbos** [comment]
I'm guessing because you should be able to use this stuff without having an RTCPeerConnection. So if webrtc-ice were adopted, webrtc-pc would no longer need RTCPeerConnection.onicecandidate. Assuming they are the same.

**Comment by aboba** [comment]
@alvestrand Both the `RTCPeerConnection` and `RTCIceTransport` have an `icecandidate` event name to provide an `RTCIceCandidate`.  For `RTCPeerConnection` the `RTCPeerConnectionIceEvent` interface is used, along with EventHandler `onicecandidate`. `RTCIceTransport` has EventHandler `onlocalcandidate`.  However, the terminology section references WebRTC-PC's `icecandidateerror`, `RTCPeerConnectionIceEvent` and `RTCPeerConnectionIceErrorEvent`. 

So it appears that the only difference is the name of the EventHandler.
