### ISSUE TITLE
addRemoteCandidate: Action on illegal candidate not specified

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-ice#19]
The specification of addRemoteCandidate() doesn't say what it should do if the candidate is malformed or otherwise illegal.

The webrtc-pc spec says that addIceCandidate() should return operationError in this case; "parameter error" would seem more logical, but consistency is probably more important than logic.

**Comment by aboba** [comment]
@alvestrand Agree that consistency is more important.  Also, for consistency, `addRemoteCandidate` should take `RTCIceCandidateInit` as an argument, rather than `RTCIceCandidate`, similar to `addIceCandidate` in WebRTC 1.0.
